### ISSUE TITLE
Error when running benchmark scripts

### ISSUE THREAD

**Issue by shua1zhang** [NVIDIA-AI-IOT/jetson_benchmarks#12]
Hi, 

I tried to run the benchmarking script on Jetson NX and nano. However I got following error on Nano. Any idea how to solve it?  Thank you.

```
shuaizh@shuaizh-nano:~/jetson_benchmarks$ sudo python3 benchmark.py --all --csv_file_path benchmark_csv/tx2-nano-benchmarks.csv --model_dir /home/shuaizh/jetson_benchmarks/models
[sudo] password for shuaizh:
Please close all other applications and Press Enter to continue...
Setting Jetson xavier-nx in max performance mode
Traceback (most recent call last):
  File "benchmark.py", line 122, in <module>
    main()
  File "benchmark.py", line 28, in main
    system_check.run_set_clocks_withDVFS()
  File "/home/shuaizh/jetson_benchmarks/utils/utilities.py", line 40, in run_set_clocks_withDVFS
    self.set_clocks_withDVFS(frequency=self.gpu_freq, device='gpu')
  File "/home/shuaizh/jetson_benchmarks/utils/utilities.py", line 61, in set_clocks_withDVFS
    from_freq = self.read_internal_register(register=self.freq_register, device=device)
  File "/home/shuaizh/jetson_benchmarks/utils/utilities.py", line 84, in read_internal_register
    reg_read = open(register, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/gpu.0/devfreq/17000000.gv11b/cur_freq'
```

**Comment by shua1zhang** [comment]
Sorry for the question, I just found on Nano different commands need to be used.
