### ISSUE TITLE
fail to run on JetPack 5.0.2, NX - FileNotFoundError: '/sys/devices/gpu.0/devfreq/17000000.gv11bnafll_gpc0/rate'

### ISSUE THREAD

**Issue by wasdee** [NVIDIA-AI-IOT/jetson_benchmarks#31]
fail to run on JetPack 5.0.2, NX
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/gpu.0/devfreq/17000000.gv11bnafll_gpc0/rate'

```
sudo python3 benchmark.py --all --csv_file_path benchmark_csv/nx-benchmarks.csv --model_dir models --jetson_devkit xavier
Please close all other applications and Press Enter to continue...
Setting Jetson xavier in max performance mode
Traceback (most recent call last):
  File "benchmark.py", line 130, in <module>
    main()
  File "benchmark.py", line 28, in main
    system_check.run_set_clocks_withDVFS()
  File "/home/redblu/jetson_benchmarks/utils/utilities.py", line 40, in run_set_clocks_withDVFS
    self.set_clocks_withDVFS(frequency=self.gpu_freq, device='gpu')
  File "/home/redblu/jetson_benchmarks/utils/utilities.py", line 74, in set_clocks_withDVFS
    from_freq = self.read_internal_register(register=freq_register_, device=device)
  File "/home/redblu/jetson_benchmarks/utils/utilities.py", line 100, in read_internal_register
    reg_read = open(register, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/gpu.0/devfreq/17000000.gv11bnafll_gpc0/rate'
```

**Comment by wasdee** [comment]
after comment out i got the same result as #28 trying the tensorrt8 branch

**Comment by wasdee** [comment]
info about `# tree /sys/devices/gpu.0/devfreq/17000000.gv11b`
```
.
├── available_frequencies
├── available_governors
├── cur_freq
├── device -> ../../../17000000.gv11b
├── governor
├── max_freq
├── min_freq
├── name
├── polling_interval
├── power
│   ├── autosuspend_delay_ms
│   ├── control
│   ├── runtime_active_time
│   ├── runtime_status
│   └── runtime_suspended_time
├── subsystem -> ../../../../../class/devfreq
├── target_freq
├── timer
├── trans_stat
└── uevent

3 directories, 17 files
```

**Comment by wasdee** [comment]
> after comment out i got the same result as #28 trying the tensorrt8 branch

The error disappeared. but there is new error about setting fan speed.
