### ISSUE TITLE
Fail to run on JetPack 4.6, Xavier-NX

### ISSUE THREAD

**Issue by dn1983** [NVIDIA-AI-IOT/jetson_benchmarks#34]
JetPack 4.6
L4T 32.6.1
Xavier-NX:

`demo@tegra-ubuntu:~/jetson_benchmarks$ sudo python3 benchmark.py --model_name inception_v4 --csv_fi_path ${PWD}/benchmark_csv/nx-benchmarks.csv --model_dir ${PWD}/models/ --power_mode 2 --jetson_devkit xavier-nx
Please close all other applications and Press Enter to continue...
Setting Jetson xavier-nx in max performance mode
Traceback (most recent call last):
  File "benchmark.py", line 130, in <module>
    main()
  File "benchmark.py", line 28, in main
    system_check.run_set_clocks_withDVFS()
  File "/home/demo/jetson_benchmarks/utils/utilities.py", line 40, in run_set_clocks_withDVFS
    self.set_clocks_withDVFS(frequency=self.gpu_freq, device='gpu')
  File "/home/demo/jetson_benchmarks/utils/utilities.py", line 74, in set_clocks_withDVFS
    from_freq = self.read_internal_register(register=freq_register_, device=device)
  File "/home/demo/jetson_benchmarks/utils/utilities.py", line 100, in read_internal_register
    reg_read = open(register, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/gpu.0/devfreq/17000000.gv11bnafll_gpc0/rate'
`

**Comment by AsawareeBhide** [comment]
Hi! Could you please try adding `--jetson_clocks` to the command? For example:

`sudo python3 benchmark.py --all --csv_file_path /benchmark_csv/tx2-nano-benchmarks.csv --model_dir /Desktop/benchmark/jetson_benchmarks/models/ --jetson_devkit nano --gpu_freq 921600000 --power_mode 0 --precision fp16  --jetson_clocks`
