### ISSUE TITLE
Fail to run on JetPack 5.1.1, Orin-NX-16Gb 

### ISSUE THREAD

**Issue by Zack0617** [NVIDIA-AI-IOT/jetson_benchmarks#37]
The benchmark failed on Orin-NX-16GB Devkit with folowing error:

orin@orin-desktop:~/jetson_benchmarks$ sudo python3 benchmark.py --all --csv_file_path /home/orin/jetson_benchmarks/benchmark_csv/orin-benchmarks.csv --model_dir /home/orin/jetson_benchmarks/models/
[sudo] password for orin: 
Please close all other applications and Press Enter to continue...
Setting Jetson orin in max performance mode
Traceback (most recent call last):
  File "benchmark.py", line 130, in <module>
    main()
  File "benchmark.py", line 28, in main
    system_check.run_set_clocks_withDVFS()
  File "/home/orin/jetson_benchmarks/utils/utilities.py", line 45, in run_set_clocks_withDVFS
    self.set_clocks_withDVFS(frequency=self.gpu_freq, device='gpu')
  File "/home/orin/jetson_benchmarks/utils/utilities.py", line 75, in set_clocks_withDVFS
    self.set_frequency(device=device, enable_register=self.enable_register, freq_register=self.freq_register, frequency=frequency, from_freq=from_freq)
  File "/home/orin/jetson_benchmarks/utils/utilities.py", line 86, in set_frequency
    self.write_internal_register(freq_register1, frequency)
  File "/home/orin/jetson_benchmarks/utils/utilities.py", line 106, in write_internal_register
    reg_write = open(register, "w")
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/bpmp/debug/clk/nafll_gpc1/rate'

**Comment by Zack0617** [comment]
Fixed with  "--jetson_clocks"

**Comment by Zack0617** [comment]
Fixed with "--jetson_clocks"
